// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"time"
)

type Entries struct {
	ID     int32         `json:"id"`
	UserID sql.NullInt32 `json:"userID"`
	RoomID sql.NullInt32 `json:"roomID"`
}

type Invitations struct {
	ID        int32          `json:"id"`
	UserID    sql.NullInt32  `json:"userID"`
	Title     string         `json:"title"`
	Place     string         `json:"place"`
	People    int32          `json:"people"`
	StartTime time.Time      `json:"startTime"`
	EndTime   time.Time      `json:"endTime"`
	Transpost string         `json:"transpost"`
	Comment   sql.NullString `json:"comment"`
	Applicant sql.NullInt32  `json:"applicant"`
	Image     sql.NullString `json:"image"`
	CreatedAt sql.NullTime   `json:"createdAt"`
}

type Messages struct {
	ID        int32         `json:"id"`
	UserID    sql.NullInt32 `json:"userID"`
	RoomID    sql.NullInt32 `json:"roomID"`
	Body      string        `json:"body"`
	IsRead    bool          `json:"isRead"`
	CreatedAt sql.NullTime  `json:"createdAt"`
}

type Photos struct {
	ID        int32          `json:"id"`
	UserID    sql.NullInt32  `json:"userID"`
	Image     sql.NullString `json:"image"`
	CreatedAt sql.NullTime   `json:"createdAt"`
}

type Rooms struct {
	ID     int32         `json:"id"`
	UserID sql.NullInt32 `json:"userID"`
}

type Users struct {
	ID             int32          `json:"id"`
	Name           string         `json:"name"`
	ProfileText    string         `json:"profileText"`
	ProfileImage   sql.NullString `json:"profileImage"`
	HeaderImage    sql.NullString `json:"headerImage"`
	CreatedAt      sql.NullTime   `json:"createdAt"`
	Email          string         `json:"email"`
	HashedPassword string         `json:"hashedPassword"`
}
