// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitations, error)
	CreatePhoto(ctx context.Context, arg CreatePhotoParams) (Photos, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (Users, error)
	DeleteInvitation(ctx context.Context, id int32) error
	DeletePhoto(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetInvitation(ctx context.Context, id int32) (Invitations, error)
	GetUser(ctx context.Context, id int32) (Users, error)
	ListInvitation(ctx context.Context, arg ListInvitationParams) ([]Invitations, error)
	ListInvitationByUser(ctx context.Context, arg ListInvitationByUserParams) ([]Invitations, error)
	ListUser(ctx context.Context, arg ListUserParams) ([]Users, error)
	UpdateInvitation(ctx context.Context, arg UpdateInvitationParams) error
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (Users, error)
	UpdateUserProfile_text(ctx context.Context, arg UpdateUserProfile_textParams) error
	UserPhotoList(ctx context.Context, arg UserPhotoListParams) ([]Photos, error)
}

var _ Querier = (*Queries)(nil)
